<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="stylesheet" href="/static/styles/MainCss.css">
</head>
<body>
<div class="image">
    <a href="/login"><img src="/static/images/EnBb.png" style="width:140px;"></a>
</div>
</body>
</html>